# Generated by Django 6.0.5 on 2026-05-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='primary_id_preview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='secondary_doc_preview',
            field=models.TextField(blank=True, default=''),
        ),
    ]
