# Generated by Django 5.2.8 on 2026-05-26 20:22

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_verificationrequest_primary_id_preview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='primary_id_preview',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='secondary_doc_preview',
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='primary_id_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.common.models.verification_document_path),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='secondary_doc_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.common.models.verification_document_path),
        ),
    ]
