# Generated by Django 6.0.5 on 2026-05-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_completion_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='schedule_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
