# Generated by Django 6.0.5 on 2026-05-26 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_completion_workflow'),
        ('reviews', '0003_review_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('author_role', 'household'), ('job__isnull', False), ('target_role', 'worker')), fields=('job', 'author', 'target'), name='unique_household_worker_review_per_job'),
        ),
    ]
